// export const FETCH_POST_STARTED = 'FETCH_POST_STARTED'
// export const FETCH_POST_FINISHED = 'FETCH_POST_FINISHED'

export const FETCH_POSTS_STARTED = 'FETCH_POSTS_STARTED'
export const FETCH_POSTS_FINISHED = 'FETCH_POSTS_FINISHED'
export const CLEAR_POST_COLLECTION = 'CLEAR_POST_COLLECTION'

export const SAVE_POST_STARTED = 'SAVE_POST_STARTED'
export const SAVE_POST_FINISHED = 'SAVE_POST_FINISHED'

export const REPORT_POST_STARTED = 'REPORT_POST_STARTED'
export const REPORT_POST_FINISHED = 'REPORT_POST_FINISHED'

export const DELETE_POST_STARTED = 'DELETE_POST_STARTED'
export const DELETE_POST_FINISHED = 'DELETE_POST_FINISHED'

export const FETCH_COMMENTS_STARTED = 'FETCH_COMMENTS_STARTED'
export const FETCH_COMMENTS_FINISHED = 'FETCH_COMMENTS_FINISHED'

export const POST_COMMENT_STARTED = 'POST_COMMENT_STARTED'
export const POST_COMMENT_FINISHED = 'POST_COMMENT_FINISHED'
export const CLEAR_NEW_COMMENT = 'CLEAR_NEW_COMMENT'

export const REPORT_COMMENT_STARTED = 'REPORT_COMMENT_STARTED'
export const REPORT_COMMENT_FINISHED = 'REPORT_COMMENT_FINISHED'

export const DELETE_COMMENT_STARTED = 'DELETE_COMMENT_STARTED'
export const DELETE_COMMENT_FINISHED = 'DELETE_COMMENT_FINISHED'

export const LIKE_POST_STARTED = 'LIKE_POST_STARTED'
export const LIKE_POST_FINISHED = 'LIKE_POST_FINISHED'
export const UNLIKE_POST_STARTED = 'UNLIKE_POST_STARTED'
export const UNLIKE_POST_FINISHED = 'UNLIKE_POST_FINISHED'

export const SHARE_POST_STARTED = 'SHARE_POST_STARTED'
export const SHARE_POST_FINISHED = 'SHARE_POST_FINISHED'

export const SET_ACTIVE_POST = 'SET_ACTIVE_POST'
export const CLEAR_ACTIVE_POST = 'CLEAR_ACTIVE_POST'

export const SET_SHARE_POST = 'SET_SHARE_POST'
export const CLEAR_SHARE_POST = 'CLEAR_SHARE_POST'
