export const FETCH_SETTINGS_STARTED = 'FETCH_SETTINGS_STARTED'
export const FETCH_SETTINGS_FINISHED = 'FETCH_SETTINGS_FINISHED'

export const FETCH_CENTRE_STARTED = 'FETCH_CENTRE_STARTED'
export const FETCH_CENTRE_FINISHED = 'FETCH_CENTRE_FINISHED'
