export const AUTHENTICATE_USER_STARTED = 'AUTHENTICATE_USER_STARTED'
export const AUTHENTICATE_USER_FINISHED = 'AUTHENTICATE_USER_FINISHED'
export const AUTHENTICATE_USER_CLEAR = 'AUTHENTICATE_USER_CLEAR'

export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE'
export const CLEAR_ACTIVE_PROFILE = 'CLEAR_ACTIVE_PROFILE'

export const CACHE_AVATAR_URL = 'CACHE_AVATAR_URL'
